# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a496a1d418eba0970a2ef53b3931892afd7fd28281d9413ff25e38ac9ba0cdfbb968897a872bb1b277ef822592c24dfdbfe178d969eb6e46746fadd4d61738e1

test:
  secret_key_base: 96b280f2b1bc82626bb68feb782fe6b395af6617c2fcf5227b1d28232062235e59ca00f492208d598858b09f021643f99930db9250b65afec4f7c5bf37525986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
